### ISSUE TITLE
Run terraform fmt on every Pull Request

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/Infrastructure#45]
This command works similarly to black.
```
terraform fmt -check -recursive -diff
```

**Comment by magul** [comment]
That will probably require us to run it in Travis?

Also does it mean that we want Makefile?

W dniu pt., 28.02.2020 o 18:00 Artur Tamborski <notifications@github.com>
napisał(a):

**Comment by magul** [comment]
Nevermind. I’ve just seen pull request.


W dniu niedz., 1.03.2020 o 14:14 Tomasz Magulski <tomasz.magulski@stxnext.pl>
napisał(a):
