### ISSUE TITLE
Prepare reusable module for our apps

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/Infrastructure#5]
I've discussed with @magul the idea to create a terraform module which configures basic set of things in AWS such as CloudFront, Certs, S3 storage, Permissions, etc.

This is very vague description because we still don't quite know what we need, so the ticket itself is left as a open question, rather than actual task. Already existing module for _v2 is a good place to get a general idea around it.

**Comment by magul** [comment]
I would say it's done. If there's something still missing we will create a separate ticket for that.
