### ISSUE TITLE
Hide secret_key resources in lambda module

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/Infrastructure#70]
That's another part of moving resources out of the top level code into appropriate modules :)

**Comment by magul** [comment]
Two thoughts here:
 * can you elaborate on this ticket? I don't really know what we want to achieve here and probably anybody watching that from outside will deliver such ticket (forgetting that usually person from outside doesn't have access to our AWS infrastructure, do you @Maciek246 know, what @arturtamborski want to deliver here?)
 * assuming, that I understand, hiding `SECRET_KEY` inside `lambda` module will not work as we have two lambdas per almost every project (one for migrations, the second one for serverless API).

**Comment by arturtamborski** [comment]
That's more complex than its worth, probably. The resource would have to be exposed from previous module so the next one could use the output variable which creates implied dependency ordering there to previously independent sections. Also, that's generally against the best practices when working with terraform code structure which I didn't knew about at that time.
Closing.
