### ISSUE TITLE
Use bastion as a NAT Gateway Instance

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/Infrastructure#86]
The reasoning here is as follows:

- We have a single VPC (default one) and a single RDS database which lives inside of that VPC.
- Database is private, no point of contact exists outside of VPC, thus our Lambdas (meaning - apps like pah, cfpv3) have to live inside of that VPC as well, which they do.
- Every lambda that lives inside of a VPC loses its internet access unless the VPC has Internet Gateway assigned, which in our case it doesn't.

Our default VPC does not have such gateway, because the cost of recommended managed gateway is astonishingly high ($35) compared with our current expenses ($15), which also means that our Lambdas do not have internet connection.

This didn't matter to us until recently, when we tried to introduce SES into cfpv3. We tried to interact with it in two ways:
- via SMTP connection
- with Boto3 (REST API)

both of these options require public internet access, because the API endpoints are internet facing.

In order to use SES and not lose the connection to DB we have to choose one of the following:

1. create AWS Managed Internet Gateway (simplest but also the most expensive option)
2. create Gateway Instance (bit more troublesome, might be insufficient in distant future, very cheap)
3. create VPC Endpoint for SES (simple, very limited compared to either of the above, not-great, not-terrible price)
4. move the DB out of VPC, assign DNS name, block unwanted traffic at the Security Group (risky, against good practices, vulnerable, free)

I spent the last few days learning about all of above options and to me it seems like the GW Instance (2) is the best one.
We would retain the full internet access, which would definitely come in useful later on when we'd work with Github and Auth0. 

Reasons against other options:
- (1) at least two times more expensive than our current monthly bill for the whole infrastructure. It might not be a lot on a larger scale, but for now that is a significant cost for a very small gain (only one lambda needs it and only for one, narrow purpose).
It's safe and scalable but that comes at too high price in my opinion. 

- (3) This option is very limiting - VPC Endpoint would let us use SES in Lambda, but only that and nothing else. If we'd want to use other AWS Services we'd have to set up another Endpoint, and the problem with no internet access would still stand (which can be solved only by 1 or 2 AFAIK). We need internet access for future integrations.

- (4) Moving the DB out is risky. It's easy to mess this up and leave the DB open to attacks, even if we set up some long secure password, also - we can't really limit the traffic between lambdas and DB itself tightly due to different management levels they are using, so the DB would be always at least a bit unsafe, especially considering that the Infra code is public.

The 2 option has an added bonus of saving money, because we could convert currently used bastion host to a GW and still retain it's purpose as a jump host. That's super cool because we're paying for it anyway, and it's $4/mo, for just sitting there and not doing much anyway. Upper limit of data transfer is somewhere around 5Gb/s, which is plenty for our use case. We could also buy a reserved instance as we did for the RDS to cut the price even more. See this link for details: https://www.kabisa.nl/tech/cost-saving-with-nat-instances/

The only problem with it is that it's:
- single place of failure for the outgoing connections (meaning SES + other future integrations)
- managed by us, which can have its down sides if someone decides to reboot or switch it off
- sparse visibility if something actually goes wrong (we could just treat is as a black box and deal with it that way)

I still think that it's the best option, for the time being. Obviously I'd love to have the managed GW and just forget about the problem but the cost forces us to consider other alternatives, and the GW Instance is the closest we can get for reasonable price.

**Comment by arturtamborski** [comment]
I'm happy to hear other opinions - @magul, @OtisRed I created that ticket to ask for a green/red light on that conversion of bastion to GW.

**Comment by OtisRed** [comment]
We should probably check if the AWS grant we are planning to get includes coverage for option 1 (for current or future reference)
